version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
    - dev
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    networks:
    - dev
volumes:
  db-data:
    driver: local
  mongo-config:
    driver: local
networks:
  dev:
    driver: bridge