version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongodb
  mongodb:
    container_name: dev-mongodb
    image: mongo:latest
    hostname: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017